# Generated by Django 3.0.4 on 2020-03-21 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_days_remaining', models.IntegerField(default=0, help_text='Days remaining with water access.')),
                ('food_days_remaining', models.IntegerField(default=0, help_text='Days remaining with food access.')),
                ('medicine_days_remaining', models.IntegerField(default=0, help_text='Days remaining with medicine access.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
